In [67]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [57]:
df = pd.read_csv("data_anime_almclean.csv", index_col="Id")["Genres"]
df = pd.DataFrame(df)
df.head(30)

                                               Genres
Id
1     Action, Adventure, Comedy, Drama, Sci-Fi, Space
5               Action, Drama, Mystery, Sci-Fi, Space
6   Action, Sci-Fi, Adventure, Comedy, Drama, Shounen
7   Action, Mystery, Police, Supernatural, Drama, ...
8           Adventure, Fantasy, Shounen, Supernatural
15                    Action, Sports, Comedy, Shounen
16       Comedy, Drama, Josei, Romance, Slice of Life
17             Slice of Life, Comedy, Sports, Shounen
18                Action, Cars, Sports, Drama, Seinen
19  Drama, Horror, Mystery, Police, Psychological,...
20  Action, Adventure, Comedy, Super Power, Martia...
21  Action, Adventure, Comedy, Super Power, Drama,...
22            Action, Comedy, Sports, School, Shounen
23                            Action, Shounen, Sports
24                   Comedy, Romance, School, Shounen
25  Action, Adventure, Comedy, Ecchi, Sci-Fi, Shounen
26               Action, Sci-Fi, Psychological, Drama
27                      Action, Supernatural, Vampire
28                                    Comedy, Shounen
29  Action, Military, Sci-Fi, Historical, Drama, S...
30  Action, Sci-Fi, Dementia, Psychological, Drama...
31                Drama, Mecha, Psychological, Sci-Fi
32      Sci-Fi, Dementia, Psychological, Drama, Mecha
33  Action, Adventure, Demons, Drama, Fantasy, Hor...
43  Action, Mecha, Police, Psychological, Sci-Fi, ...
44  Action, Historical, Drama, Romance, Martial Ar...
45  Action, Adventure, Comedy, Historical, Romance...
46                Samurai, Historical, Drama, Shounen
47  Action, Military, Sci-Fi, Adventure, Horror, S...
48   Game, Sci-Fi, Adventure, Mystery, Magic, Fantasy

In [58]:
def clean_genres(genres):
    genre_list = genres.split(', ')
    cleaned_genres = []
    if len(genre_list) == 1:
        genre_list[0] = genre_list[0]
    for genre in genre_list:
        m_len = int(len(genre)/2)
        if genre[:m_len] == genre[m_len:]:
            cleaned_genres.append(genre[:m_len])
        else:
            parts = genre.split()
            if len(parts) == 2 and parts[0] == parts[1]:
                cleaned_genres.append(parts[0])
            else:
                cleaned_genres.append(genre)

    return ', '.join(cleaned_genres)

df['Genres'] = df['Genres'].apply(clean_genres)
df.head(30)

                                               Genres
Id
1     Action, Adventure, Comedy, Drama, Sci-Fi, Space
5               Action, Drama, Mystery, Sci-Fi, Space
6   Action, Sci-Fi, Adventure, Comedy, Drama, Shounen
7   Action, Mystery, Police, Supernatural, Drama, ...
8           Adventure, Fantasy, Shounen, Supernatural
15                    Action, Sports, Comedy, Shounen
16       Comedy, Drama, Josei, Romance, Slice of Life
17             Slice of Life, Comedy, Sports, Shounen
18                Action, Cars, Sports, Drama, Seinen
19  Drama, Horror, Mystery, Police, Psychological,...
20  Action, Adventure, Comedy, Super Power, Martia...
21  Action, Adventure, Comedy, Super Power, Drama,...
22            Action, Comedy, Sports, School, Shounen
23                            Action, Shounen, Sports
24                   Comedy, Romance, School, Shounen
25  Action, Adventure, Comedy, Ecchi, Sci-Fi, Shounen
26               Action, Sci-Fi, Psychological, Drama
27                      Action, Supernatural, Vampire
28                                    Comedy, Shounen
29  Action, Military, Sci-Fi, Historical, Drama, S...
30  Action, Sci-Fi, Dementia, Psychological, Drama...
31                Drama, Mecha, Psychological, Sci-Fi
32      Sci-Fi, Dementia, Psychological, Drama, Mecha
33  Action, Adventure, Demons, Drama, Fantasy, Hor...
43  Action, Mecha, Police, Psychological, Sci-Fi, ...
44  Action, Historical, Drama, Romance, Martial Ar...
45  Action, Adventure, Comedy, Historical, Romance...
46                Samurai, Historical, Drama, Shounen
47  Action, Military, Sci-Fi, Adventure, Horror, S...
48   Game, Sci-Fi, Adventure, Mystery, Magic, Fantasy

In [59]:
df.loc[9260]

Genres    Vampire
Name: 9260, dtype: object

In [60]:
df['Genres'] = df['Genres'].str.split(', ')
df

                                                  Genres
Id
1      [Action, Adventure, Comedy, Drama, Sci-Fi, Space]
5                [Action, Drama, Mystery, Sci-Fi, Space]
6      [Action, Sci-Fi, Adventure, Comedy, Drama, Sho...
7      [Action, Mystery, Police, Supernatural, Drama,...
8            [Adventure, Fantasy, Shounen, Supernatural]
...                                                  ...
48417                           [Magic, Fantasy, School]
48418           [Action, Demons, Magic, Fantasy, School]
48438           [Slice of Life, Magic, Fantasy, Shounen]
48456                                   [Comedy, Sports]
48491                 [Adventure, Slice of Life, Comedy]

[12019 rows x 1 columns]

In [61]:
all_genres = set(genre for genres_list in df['Genres'] for genre in genres_list)
for genre in all_genres:
    df[genre] = 0

df

,Genres,Kids,Ecchi,Demons,Police,Shounen Ai,Shoujo,Romance,Samurai,Fantasy,...,Shoujo Ai,Yaoi,Psychological,Cars,Music,Vampire,Yuri,Slice of Life,Magic,Harem
Id,,,,,,,,,,,,,,,,,,,,,
1,"[Action, Adventure, Comedy, Drama, Sci-Fi, Space]",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,"[Action, Drama, Mystery, Sci-Fi, Space]",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,"[Action, Sci-Fi, Adventure, Comedy, Drama, Sho...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,"[Action, Mystery, Police, Supernatural, Drama,...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,"[Adventure, Fantasy, Shounen, Supernatural]",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48417,"[Magic, Fantasy, School]",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48418,"[Action, Demons, Magic, Fantasy, School]",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48438,"[Slice of Life, Magic, Fantasy, Shounen]",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48456,"[Comedy, Sports]",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48491,"[Adventure, Slice of Life, Comedy]",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [62]:

for index, row in df.iterrows():
    genres_list = row['Genres']
    for genre in genres_list:
        df.at[index, genre] = 1

df.drop(columns=['Genres'], inplace=True)

print(df)

       Kids  Ecchi  Demons  Police  Shounen Ai  Shoujo  Romance  Samurai  \
Id
1         0      0       0       0           0       0        0        0
5         0      0       0       0           0       0        0        0
6         0      0       0       0           0       0        0        0
7         0      0       0       1           0       0        0        0
8         0      0       0       0           0       0        0        0
...     ...    ...     ...     ...         ...     ...      ...      ...
48417     0      0       0       0           0       0        0        0
48418     0      0       1       0           0       0        0        0
48438     0      0       0       0           0       0        0        0
48456     0      0       0       0           0       0        0        0
48491     0      0       0       0           0       0        0        0

       Fantasy  Parody  ...  Shoujo Ai  Yaoi  Psychological  Cars  Music  \
Id                      ...
1            0       0  ...          0     0              0     0      0
5            0       0  ...          0     0              0     0      0
6            0       0  ...          0     0              0     0      0
7            0       0  ...          0     0              0     0      0
8            1       0  ...          0     0              0     0      0
...        ...     ...  ...        ...   ...            ...   ...    ...
48417        1       0  ...          0     0              0     0      0
48418        1       0  ...          0     0              0     0      0
48438        1       0  ...          0     0              0     0      0
48456        0       0  ...          0     0              0     0      0
48491        0       0  ...          0     0              0     0      0

       Vampire  Yuri  Slice of Life  Magic  Harem
Id
1            0     0              0      0      0
5            0     0              0      0      0
6            0     0              0      0      0
7            0     0              0      1      0
8            0     0              0      0      0
...        ...   ...            ...    ...    ...
48417        0     0              0      1      0
48418        0     0              0      1      0
48438        0     0              1      1      0
48456        0     0              0      0      0
48491        0     0              1      0      0

[12019 rows x 44 columns]

In [65]:
df

,Kids,Ecchi,Demons,Police,Shounen Ai,Shoujo,Romance,Samurai,Fantasy,Parody,...,Shoujo Ai,Yaoi,Psychological,Cars,Music,Vampire,Yuri,Slice of Life,Magic,Harem
Id,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
8,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48417,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
48418,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
48438,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,1,0
48456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48491,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [70]:
def find_similar_ids(df, target_id, num_similar=20):
    target_genres = df.loc[target_id, :].values.reshape(1, -1)
    similarities = cosine_similarity(target_genres, df.values)
    similar_indices = similarities.argsort()[0][::-1][1:num_similar + 1]
    similar_ids = df.index[similar_indices].tolist()

    return similar_ids

In [75]:
df.loc[1]

Kids             0
Ecchi            0
Demons           0
Police           0
Shounen Ai       0
Shoujo           0
Romance          0
Samurai          0
Fantasy          0
Parody           0
Horror           0
Adventure        1
Dementia         0
Shounen          0
Supernatural     0
Mecha            0
Martial Arts     0
Action           1
Super Power      0
Comedy           1
Seinen           0
Hentai           0
School           0
Sci-Fi           1
Game             0
Military         0
Josei            0
Thriller         0
Drama            1
Historical       0
Unknown          0
Sports           0
Space            1
Mystery          0
Shoujo Ai        0
Yaoi             0
Psychological    0
Cars             0
Music            0
Vampire          0
Yuri             0
Slice of Life    0
Magic            0
Harem            0
Name: 1, dtype: int64

In [71]:
similar_ids = find_similar_ids(df, target_id=1, num_similar=20)
similar_ids

[4037,
 1226,
 2717,
 400,
 2202,
 1287,
 2203,
 1490,
 2470,
 1920,
 1921,
 6,
 1620,
 1650,
 3069,
 1293,
 1481,
 1184,
 1168,
 1645]

In [76]:
df.to_csv("anime_genres.csv", index=True)