In [40]:
import pandas as pd

In [41]:
df = pd.read_csv("dirty_anime.csv")
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df.head(5)

/var/folders/kw/6b3fdnzn0135l99wq600vfy80000gn/T/ipykernel_4741/2976499967.py:1: DtypeWarning: Columns (19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("dirty_anime.csv")

,index,rec_1,rec_2,rec_3,rec_5,rec_6,rec_7,rec_8,rec_9,rec_10,...,Licensors,Studios,Source,Genres,Themes,Demographic,Duration,Rating,Related_content,rec_4
0,1550,Haikyuu!!,Tiger Mask,Ashita no Joe,NaN,NaN,NaN,NaN,NaN,NaN,...,"Studios, \nTokyo Movie Shinsha","Source, \n Manga","Genres, \nDramaDrama, SportsSports","Theme, \nTeam SportsTeam Sports","Demographic, \nShoujoShoujo","Duration, \n 24 min. per ep.","Rating, \n PG-13 - Teens 13 or older","Score, \n7.001 (scored by 38703,870 users)\n ...","Adaptation:: /manga/10199/Attack_No1, Summary:...",NaN
1,9163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Genres, \nDramaDrama, SportsSports","Theme, \nTeam SportsTeam Sports","Demographic, \nShoujoShoujo","Duration, \n 1 hr. 5 min.","Rating, \n PG-13 - Teens 13 or older","Score, \n6.361 (scored by 440440 users)\n ...","Ranked, \n #75552\n\n2\n based on the top ...","Popularity, \n #12229",Full story:: /anime/1550/Attack_No1,NaN
2,2830,Panda Kopanda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Genres, \nAdventureAdventure, DramaDra...","Duration, \n 1 hr. 21 min.","Rating, \n G - All Ages","Score, \n5.841 (scored by 330330 users)\n ...","Ranked, \n #101502\n\n2\n based on the top...","Popularity, \n #12958","Members, \n 1,113","Favorites, \n 1",Alternative version:: /anime/2828/Ie_Naki_Ko,NaN
3,18061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Theme, \nCombat SportsCombat Sports","Demographic, \nShounenShounen","Duration, \n 47 min.","Rating, \n PG-13 - Teens 13 or older","Score, \n6.221 (scored by 284284 users)\n ...","Ranked, \n #83312\n\n2\n based on the top ...","Popularity, \n #13008","Members, \n 1,095","Adaptation:: /manga/30575/Tiger_Mask, Full sto...",NaN
4,12789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Genres, \nAward WinningAward Winning, ...","Theme, \nMusicMusic","Demographic, \nKidsKids","Duration, \n 27 min.","Rating, \n G - All Ages","Score, \n5.461 (scored by 467467 users)\n ...","Ranked, \n #115942\n\n2\n based on the top...","Popularity, \n #13289",NaN,NaN

In [42]:
df.columns

Index(['index', 'rec_1', 'rec_2', 'rec_3', 'rec_5', 'rec_6', 'rec_7', 'rec_8',
       'rec_9', 'rec_10', 'staff_1', 'staff_2', 'staff_3', 'staff_4', 'Title',
       'Ranked', 'Popularity', 'Members', 'PositiveReviews', 'MixedReviews',
       'NegativeReviews', 'Staff', 'Type', 'Episodes', 'Status', 'Aired',
       'Producers', 'Licensors', 'Studios', 'Source', 'Genres', 'Themes',
       'Demographic', 'Duration', 'Rating', 'Related_content', 'rec_4'],
      dtype='object')

In [43]:
len(df)

70772

In [44]:
word = "Themes, ParodyParody,         SchoolSchool"

In [45]:
def removeDupes(x):
    final = []
    lst = x.split(",")
    for i in lst:
        y = i.strip()
        z = int(len(y)/2)

        if y[:z] == y[z:]:
            final.append(y[z:])
        else:
            final.append(y)
    return ','.join(final)

In [46]:
removeDupes(word)

'Themes,Parody,School'

In [47]:
df.Licensors = df.Licensors.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
df.Licensors = df.Licensors.apply(removeDupes)
df.Licensors

0                 Studios,Tokyo Movie Shinsha
1                         Genres,Drama,Sports
2        Genres,Adventure,Drama,Slice of Life
3                         Theme,Combat Sports
4                Genres,Award Winning,Fantasy
                         ...
70767                            Source,Manga
70768              Studios,Studio Eight Color
70769                            Genre,Sports
70770                        Theme,Historical
70771                    Themes,Parody,School
Name: Licensors, Length: 70772, dtype: object

In [48]:
df.Studios = df.Studios.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
df.Studios = df.Studios.apply(removeDupes)
df.Studios

0                  Source,Manga
1             Theme,Team Sports
2        Duration,1 hr. 21 min.
3           Demographic,Shounen
4                   Theme,Music
                  ...
70767          Duration,Unknown
70768          Source,Web manga
70769         Theme,Team Sports
70770          Duration,Unknown
70771          Duration,Unknown
Name: Studios, Length: 70772, dtype: object

In [49]:
df.Source = df.Source.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
df.Source = df.Source.apply(removeDupes)
df.Source

0                     Genres,Drama,Sports
1                      Demographic,Shoujo
2                     Rating,G - All Ages
3                        Duration,47 min.
4                        Demographic,Kids
                       ...
70767                         Rating,None
70768                        Genre,Comedy
70769                    Duration,Unknown
70770                         Rating,None
70771    Rating,PG-13 - Teens 13 or older
Name: Source, Length: 70772, dtype: object

In [50]:
df.Genres = df.Genres.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
df.Genres = df.Genres.apply(removeDupes)
df.Genres

0                                        Theme,Team Sports
1                                    Duration,1 hr. 5 min.
2        Score,5.841 (scored by 330330 users)      1   ...
3                         Rating,PG-13 - Teens 13 or older
4                                         Duration,27 min.
                               ...
70767    Score,N/A1 (scored by - users)      1         ...
70768                            Themes,Pets,Reincarnation
70769                                          Rating,None
70770    Score,N/A1 (scored by - users)      1         ...
70771    Score,N/A1 (scored by - users)      1         ...
Name: Genres, Length: 70772, dtype: object

In [51]:
df.Related_content = df.Related_content.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
df.Related_content = df.Related_content.apply(removeDupes)
df.Related_content

0        Adaptation:: /manga/10199/Attack_No1,Summary::...
1                      Full story:: /anime/1550/Attack_No1
2             Alternative version:: /anime/2828/Ie_Naki_Ko
3        Adaptation:: /manga/30575/Tiger_Mask,Full stor...
4                                                      nan
                               ...
70767    Adaptation:: /manga/168772/Duel_Masters_LOST__...
70768    Adaptation:: /manga/163337/Neko_ni_Tensei_shit...
70769                                                  nan
70770                 Other:: /anime/1199/Nintama_Rantarou
70771    Adaptation:: /manga/121209/Houkago_Shounen_Han...
Name: Related_content, Length: 70772, dtype: object

In [52]:
df.columns

Index(['index', 'rec_1', 'rec_2', 'rec_3', 'rec_5', 'rec_6', 'rec_7', 'rec_8',
       'rec_9', 'rec_10', 'staff_1', 'staff_2', 'staff_3', 'staff_4', 'Title',
       'Ranked', 'Popularity', 'Members', 'PositiveReviews', 'MixedReviews',
       'NegativeReviews', 'Staff', 'Type', 'Episodes', 'Status', 'Aired',
       'Producers', 'Licensors', 'Studios', 'Source', 'Genres', 'Themes',
       'Demographic', 'Duration', 'Rating', 'Related_content', 'rec_4'],
      dtype='object')

In [53]:
df.iloc[60000:60010][['Title', 'Related_content', 'Genres']]

,Title,Related_content,Genres
60000,Supernatural The Animation,nan,"Duration,24 min. per ep."
60001,Fortune Arterial: Akai Yakusoku - Tadoritsuita...,"Adaptation:: /manga/6320/Fortune_Arterial,Preq...","Rating,PG-13 - Teens 13 or older"
60002,Nana to Kaoru,Adaptation:: /manga/5994/Nana_to_Kaoru,"Duration,24 min."
60003,Queen's Blade: Utsukushiki Toushi-tachi,Prequel:: /anime/6633/Queens_Blade__Gyokuza_wo...,"Rating,R+ - Mild Nudity"
60004,Aa! Megami-sama! (2011),"Adaptation:: /manga/446/Aa_Megami-sama,Other::...","Duration,28 min. per ep."
60005,Sweet Home: H na Oneesan wa Suki desu ka?,nan,"Rating,Rx - Hentai"
60006,Ane Jiru 2 The Animation: Shirakawa Sanshimai ...,Adaptation:: /manga/74115/Anejiru__Shirakawa_S...,"Score,6.891 (scored by 55195,519 users) 1..."
60007,Hakuouki OVA,"Adaptation:: /manga/24656/Hakuouki_SSL,Other::...","Rating,PG-13 - Teens 13 or older"
60008,Saiyuuki Gaiden,"Adaptation:: /manga/1097/Saiyuuki_Gaiden,Seque...","Duration,29 min. per ep."
60009,Kaibutsu Oujo (OVA),"Adaptation:: /manga/424/Kaibutsu_Oujo,Alternat...","Rating,R - 17+ (violence & profanity)"

In [54]:
df.iloc[64000:64020]['Related_content']

64000                                                  nan
64001                       Sequel:: /anime/40570/The_Peak
64002                                                  nan
64003                                                  nan
64004    Alternative version:: /anime/7461/Komaneko_no_...
64005                                                  nan
64006    Sequel:: /anime/37643/Xiong_Bing_Lian,Prequel:...
64007    Other:: /anime/34741/Tomica_Hyper_Rescue_Drive...
64008                                                  nan
64009    Sequel:: /anime/53392/Mei_Shaonu_Da_Picha_2nd_...
64010    Adaptation:: /manga/144894/Kimagure_Concept_Ch...
64011           Parent story:: /anime/46864/Cha_A_Er_Zhong
64012    Prequel:: /anime/47199/Juedui_Lingyu_A_F,Side ...
64013    Prequel:: /anime/45335/Bing_Ji_Chaoren_Kuaidi_Xia
64014                                                  nan
64015                                                  nan
64016                                                  nan
64017                                                  nan
64018                                                  nan
64019                                                  nan
Name: Related_content, dtype: object

In [81]:
df.iloc[35247]

index                                                           6730
rec_1                                                            NaN
rec_2                                                            NaN
rec_3                                                            NaN
rec_5                                                            NaN
rec_6                                                            NaN
rec_7                                                            NaN
rec_8                                                            NaN
rec_9                                                            NaN
rec_10                                                           NaN
staff_1                               Kodama, Kenji:Episode Director
staff_2                                Iuchi, Shuji:Episode Director
staff_3                                Aoki, Yuuzou:Episode Director
staff_4                                Suda, Yumiko:Episode Director
Title                                                   Tonde Mon Pe
Ranked                                                         #6813
Popularity                                                    #16141
Members                                                          478
PositiveReviews                                                    0
MixedReviews                                                       0
NegativeReviews                                                    0
Staff              ['Kodama, Kenji', 'Episode Director'], ['Iuchi...
Type                                                Episodes, \n  42
Episodes                                 Status, \n  Finished Airing
Status                         Aired, \n  Jun 5, 1982 to Apr 2, 1983
Aired                                       Premiered, \nSummer 1982
Producers                      Licensors, \n    None found, add some
Licensors                                Studios,None found,add some
Studios                                               Source,Unknown
Source                                            Genre,Supernatural
Genres                                               Theme,Childcare
Themes                                       Demographic, \nKidsKids
Demographic                            Duration, \n  23 min. per ep.
Duration                                    Rating, \n  G - All Ages
Rating             Score, \n6.501 (scored by 121121 users)\n     ...
Related_content                                                  nan
rec_4                                                            NaN
Prequel                                                            0
Hentai                                                             0
Name: 35247, dtype: object

In [56]:
df['Prequel'] = 0

In [57]:
x = "Prequel:: /anime/45335/Bing_Ji_Chaoren_Kuaidi_Xia"
x

'Prequel:: /anime/45335/Bing_Ji_Chaoren_Kuaidi_Xia'

In [58]:
def find_prequel(w):
    for j in w.split(","):
        for i in j.split(":"):
            if i == 'Prequel':
                return 1
    return 0

def find_hentai(w):
    for i in w.split(" "):
        if i == 'Hentai':
            return 1
    return 0

In [59]:
df['Prequel'] = df['Related_content'].apply(find_prequel)
df['Prequel']

0        0
1        0
2        0
3        0
4        0
        ..
70767    0
70768    0
70769    0
70770    0
70771    1
Name: Prequel, Length: 70772, dtype: int64

In [60]:
df[df['Prequel'] == 1]['Title']

8                                            Ashita no Joe
43                                               Lupin III
52                                   Shin Obake no Q-tarou
53                                           Shin Skyers 5
70                       Ryuuichi Manga Gekijou Onbu Obake
                               ...
70760    Shin Tennis no Oujisama: U-17 World Cup Semifinal
70761                                 Kamierabi 2nd Season
70764               The iDOLM@STER Shiny Colors 2nd Season
70766                          Hyakushou Kizoku 2nd Season
70771                Houkago Shounen Hanako-kun (Zoku-hen)
Name: Title, Length: 11205, dtype: object

In [61]:
df[df['index'] == 28977]

,index,rec_1,rec_2,rec_3,rec_5,rec_6,rec_7,rec_8,rec_9,rec_10,...,Studios,Source,Genres,Themes,Demographic,Duration,Rating,Related_content,rec_4,Prequel
10925,28977,SKET Dance,One Punch Man,Saiki Kusuo no Î¨-nan,Grand Blue,JoJo no Kimyou na Bouken Part 4: Diamond wa Ku...,One Piece,Katekyou Hitman Reborn!,Boku no Tonari ni Ankoku Hakaishin ga Imasu.,Clannad: After Story,...,"Studios,Bandai Namco Pictures","Source,Manga","Genres,Action,Comedy,Sci-Fi","Themes, \nGag HumorGag Humor, Historic...","Demographic, \nShounenShounen","Duration, \n 24 min. per ep.","Rating, \n PG-13 - Teens 13 or older","Adaptation:: /manga/44/Gintama,Prequel:: /anim...",Baka to Test to Shoukanjuu,1
28290,28977,SKET Dance,One Punch Man,Saiki Kusuo no Î¨-nan,Grand Blue,JoJo no Kimyou na Bouken Part 4: Diamond wa Ku...,One Piece,Katekyou Hitman Reborn!,Boku no Tonari ni Ankoku Hakaishin ga Imasu.,Clannad: After Story,...,"Studios,Bandai Namco Pictures","Source,Manga","Genres,Action,Comedy,Sci-Fi","Themes, \nGag HumorGag Humor, Historic...","Demographic, \nShounenShounen","Duration, \n 24 min. per ep.","Rating, \n PG-13 - Teens 13 or older","Adaptation:: /manga/44/Gintama,Prequel:: /anim...",Baka to Test to Shoukanjuu,1
45655,28977,SKET Dance,One Punch Man,Saiki Kusuo no Î¨-nan,Grand Blue,JoJo no Kimyou na Bouken Part 4: Diamond wa Ku...,One Piece,Katekyou Hitman Reborn!,Boku no Tonari ni Ankoku Hakaishin ga Imasu.,Clannad: After Story,...,"Studios,Bandai Namco Pictures","Source,Manga","Genres,Action,Comedy,Sci-Fi","Themes, \nGag HumorGag Humor, Historic...","Demographic, \nShounenShounen","Duration, \n 24 min. per ep.","Rating, \n PG-13 - Teens 13 or older","Adaptation:: /manga/44/Gintama,Prequel:: /anim...",Baka to Test to Shoukanjuu,1
63020,28977,SKET Dance,One Punch Man,Saiki Kusuo no Î¨-nan,Grand Blue,JoJo no Kimyou na Bouken Part 4: Diamond wa Ku...,One Piece,Katekyou Hitman Reborn!,Boku no Tonari ni Ankoku Hakaishin ga Imasu.,Clannad: After Story,...,"Studios,Bandai Namco Pictures","Source,Manga","Genres,Action,Comedy,Sci-Fi","Themes, \nGag HumorGag Humor, Historic...","Demographic, \nShounenShounen","Duration, \n 24 min. per ep.","Rating, \n PG-13 - Teens 13 or older","Adaptation:: /manga/44/Gintama,Prequel:: /anim...",Baka to Test to Shoukanjuu,1

In [62]:
df.columns

Index(['index', 'rec_1', 'rec_2', 'rec_3', 'rec_5', 'rec_6', 'rec_7', 'rec_8',
       'rec_9', 'rec_10', 'staff_1', 'staff_2', 'staff_3', 'staff_4', 'Title',
       'Ranked', 'Popularity', 'Members', 'PositiveReviews', 'MixedReviews',
       'NegativeReviews', 'Staff', 'Type', 'Episodes', 'Status', 'Aired',
       'Producers', 'Licensors', 'Studios', 'Source', 'Genres', 'Themes',
       'Demographic', 'Duration', 'Rating', 'Related_content', 'rec_4',
       'Prequel'],
      dtype='object')

In [63]:
df['Hentai'] = df['Genres'].apply(find_hentai)
df[df['Hentai'] == 1]['Title']

642                                           Lolita Anime
677                                            Cream Lemon
755                                  Telepathist IQ Psycho
757                                       Punky Funky Baby
772                                SF Lolita Fantasy Ome-1
                               ...
68133        Jimihen!! Jimiko wo Kaechau Jun Isei Kouyuu!!
68949    3-byougo, Yajuu. Goukon de Sumi ni Ita Kare wa...
69546    Kemonokko Tsuushin: The Animation - Nekomusume...
69922                Sazanami Soushi ni Junketsu wo Sasagu
70100                         Fuufu Koukan: Modorenai Yoru
Name: Title, Length: 943, dtype: object

In [64]:
jojo_df = df[['index', 'Hentai', 'Prequel']]
jojo_df.columns = ['Id', 'Hentai', 'Prequel']
jojo_df = jojo_df.drop_duplicates()
jojo_df.sort_values('Id').head(20)

      Id  Hentai  Prequel
2969   1       0        0
3824   5       0        0
2970   6       0        0
4130   7       0        0
4920   8       0        0
5068  15       0        0
5064  16       0        0
4212  17       0        0
4709  18       0        1
4706  19       0        0
4203  20       0        0
3324  21       0        0
3856  22       0        0
4930  23       0        0
4895  24       0        0
4900  25       0        0
4369  26       0        0
5067  27       0        0
4906  28       0        0
4917  29       0        0

In [65]:
anime_df = pd.read_csv("../../apis/data/data4filter.csv")
anime_df.head(3)

   Id  Score  Episodes  Min_Duration  Year
0   1   8.78        26          24.0  1998
1   5   8.39         1         115.0  2001
2   6   8.24        26          24.0  1998

In [66]:
anime_df.set_index('Id')

       Score  Episodes  Min_Duration  Year
Id
1       8.78        26          24.0  1998
5       8.39         1         115.0  2001
6       8.24        26          24.0  1998
7       7.27        26          25.0  2002
8       6.98        52          23.0  2004
...      ...       ...           ...   ...
47778    NaN      1000           0.0  2021
48438    NaN         3           0.0  2021
48456   6.52         1          23.0  2021
48483    NaN      1000           0.0  2021
48488    NaN      1000           0.0  2021

[6680 rows x 4 columns]

In [67]:
final_df = anime_df.merge(jojo_df, how="left", on="Id")
final_df

         Id  Score  Episodes  Min_Duration  Year  Hentai  Prequel
0         1   8.78        26          24.0  1998     0.0      0.0
1         5   8.39         1         115.0  2001     0.0      0.0
2         6   8.24        26          24.0  1998     0.0      0.0
3         7   7.27        26          25.0  2002     0.0      0.0
4         8   6.98        52          23.0  2004     0.0      0.0
...     ...    ...       ...           ...   ...     ...      ...
6689  47778    NaN      1000           0.0  2021     0.0      1.0
6690  48438    NaN         3           0.0  2021     0.0      0.0
6691  48456   6.52         1          23.0  2021     0.0      0.0
6692  48483    NaN      1000           0.0  2021     0.0      0.0
6693  48488    NaN      1000           0.0  2021     0.0      1.0

[6694 rows x 7 columns]

In [71]:
final_df[final_df['Id'] == 35247]

         Id  Score  Episodes  Min_Duration  Year  Hentai  Prequel
5463  35247   8.93         7          22.0  2017     0.0      0.0

In [69]:
final_df.to_csv("../../apis/data/data4filter2.csv", index=False)

In [70]:
jojo_df = jojo_df.sort_values("Id").reset_index()
jojo_df = jojo_df.drop(['level_0', 'index'], axis=1)
jojo_df

KeyError: "['level_0'] not found in axis"

In [ ]:
mdf.to_csv("../../apis/data/data4filter2.csv", index=False)

In [ ]:
h = True
print(int(h))

1